name: react-starter-ci

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [20]
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v4
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install Depedencies
              run: pnpm i

            - name: Lint Code
              run: make lint

            - name: Typecheck Code
              run: make typecheck

            - name: Check Format Code
              run: make format-check

            - name: Test
              run: make test

            - name: Compile production-ready code
              run: make build-production
